basestations:
- 1
- 2
- 3
batch_size:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
- 50
- 51
- 52
- 53
- 54
- 55
- 56
- 57
- 58
- 59
- 60
- 61
- 62
- 63
camera: true
camera_id:
- 1
- 2
- 3
- 4
- 5
comm:
  OFDM_sampling:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  activate_RX_filter: 0
  ant_FoV_BS:
  - 360
  - 180
  ant_FoV_UE:
  - 360
  - 180
  ant_spacing_BS: 0.5
  ant_spacing_UE: 0.5
  array_rotation_BS:
  - 5
  - 10
  - 20
  array_rotation_UE:
  - 0
  - 30
  - 0
  bandwidth: 0.05
  enable: true
  enable_Doppler: 1
  generate_OFDM_channels: 1
  num_OFDM: 512
  num_ant_BS:
  - 32
  - 1
  num_ant_UE:
  - 1
  - 1
  num_paths: 25
dataset_folder: scenarios
lidar: true
position: true
radar:
  Fs: 4000000.0
  N_chirp: 128
  N_samples: 512
  S: 15000000000000.0
  ant_FoV_RX:
  - 180
  - 180
  ant_FoV_TX:
  - 180
  - 180
  ant_spacing_RX: 0.5
  ant_spacing_TX: 0.5
  array_rotation_RX:
  - 0
  - 0
  - -90
  array_rotation_TX:
  - 0
  - 0
  - -90
  comp_speed: 4
  enable: true
  num_ant_RX:
  - 32
  - 1
  num_ant_TX:
  - 1
  - 1
  num_paths: 5000
scenario: Scenario 1
scenes:
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
- 50
- 51
- 52
- 53
- 54
- 55
- 56
- 57
- 58
- 59
- 60
- 61
- 62
- 63
- 64
- 65
- 66
- 67
- 68
- 69
- 70
- 71
- 72
- 73
- 74
- 75
- 76
- 77
- 78
- 79
- 80
- 81
- 82
- 83
- 84
- 85
- 86
- 87
- 88
- 89
- 90
- 91
- 92
- 93
- 94
- 95
- 96
- 97
- 98
- 99
- 100
